### PR TITLE
Code overhaul, support for "pdf2djvu"

### PR DESCRIPTION
**Pull request by pirtim**
Hello, I did an overhaul of this code and added support for second backend - `pdf2djvu`. From my tests on cygwin it's just 0-10% worse than `djvudigital` in terms of output file's size. I didn't measure time difference but it was imperceptible.

Main changes:
* code modernization
* `pdf2djvu` backend support added (with installation scripts for Windows)
* proper CLI support added
* `convert_all` works for current Calibre (it didn't with version 1.0.2)
* convert by ID also works now
* a lot of documentation added
* conversion can be aborted from GUI
* during conversion with `pdf2djvu`, GUI shows progress report
* "fix" for bug during `image_count` in `is_rasterbook`
* better support for `configure plugin` menu inside Calibre GUI
* more concise printing
* changes to `README.md` and minor change to `Makefile`

For your consideration:
* I would ask you to do tests on macOS with `djvudigital`. I cannot do that by myself.
* installation script for pdf2djvu for Windows manually downloads files from author's github [page](https://github.com/jwilk/pdf2djvu) - maybe we should add some big warning info about downloading from untrusted sources?
* other possibility is just to add `pdf2djvu` executable to this repo. It's licensed on GPL 2, which is compatible with GPL 3.
* I'm not sure if postimport still works for macOS with `djvudigital`, but it could be broken because of Calibre updates.
* I squashed some of my commits to make diffs more readable. I can make one _super-commit_ if you want but I think it would be unreadable.

### CODE REVIEW

**Comment by kfix** [comment]
Thanks for the contribution!
I haven't used this an awhile but I can test it on my Mac at home after I update Calibre.

**Comment by kfix** [comment]
I tested the djvudigital backend and it still worked.
I could not get pdf2djvu built on Mac, due to GNU Autohell.

I think its okay to merge, but I'll need to refresh myself on how the release/publishing process works and if we can gate 1.1 to only a certain threshold of Calibre versions (after 2.68?)

**Comment by pirtim** [comment]
I've just tested v1.1.0 on Calibre 2.22.0 and it works fine.

----

If you still wants to gate this for certain Calibre version, we can change this line:
```python
# __init__.py:300
minimum_calibre_version = (2, 22, 0)
```
but I'm not sure if would be still possible to download automatically version 1.0.2 from Calibre's preferences menu.

Other possibility is to test Calibre's version inside code with:
```python
from calibre.constants import numeric_version
if numeric_version > (2,68,0):
     from calibre_plugins.djvumaker.__init__new import DJVUmaker
else:
     from calibre_plugins.djvumaker.__init__old import DJVUmaker
```
but I think it would be overkill.

----
As you can see I pushed small fix. Unfortunately `sys.__stdin__.isatty()` does not recognise some shells (e.g. cygwin) so for `convert --all` it still goes to `fork_job` (for 1.0.2 too).

**Comment by pirtim** [comment]
Ping. Any progress? Do you need any help with this?

**Comment by kfix** [comment]
Sorry, busy with $JOB. I think I had some issue with using pdf2djvu on OSX which I would like to be seamless. I'll merge as is now and put my OS X updates on top and retag afterwards for release. Cool?

**Comment by pirtim** [comment]
Yeah, sure.

**Pull request merged**
